substitutions:
  friendly_name: "ESP32-CAM 46c474"

packages:
  device: !include ./device_headers/esp32-cam-46c474.yaml

psram:

i2c:
  - id: camera_i2c
    sda: GPIO26
    scl: GPIO27

esp32_camera:
  name: OV2640
  external_clock:
    pin: GPIO0
    frequency: 10MHz
  i2c_id: camera_i2c
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  # Image/Video settings, https://esphome.io/components/esp32_camera.html
  max_framerate: 25 fps    # default: 10 fps, max 60
  idle_framerate: 0.2 fps # default: 0.1 fps - framerate for 'picture' in HA dashboard
  resolution: 1024x768
  jpeg_quality: 10
  vertical_flip: False
  contrast: 0 # default: 0, variable -2 to 2
  brightness: 0 # default: 0, variable -2 to 2
  saturation: 0 # default: 0, variable -2 to 2

time:
  - platform: homeassistant
    id: homeassistant_time

output:
#flashlight
  - platform: gpio
    pin: GPIO4
    id: gpio_4

light:
#flashlight
  - platform: binary
    output: gpio_4
    name: Light
