substitutions: 
  friendly_name: "ESP32-CAM-46c474"

esphome:
  name: esp32-cam-46c474
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp32:
  board: esp32cam
  framework:
    type: arduino
    
captive_portal:

api:
  encryption:
    key: !secret esp32-cam_api_encryption_key

ota:
  - platform: esphome
    password: !secret esp32-cam_ota_password

logger:

packages:
  diagnostics: !include ../device_config/diagnostics.yaml
  wifi: !include ../device_config/wifi.yaml
  status_led: !include
    file: ../modules/status_led/status_led.yaml
    vars:
      pin_number: GPIO33
      pin_inverted: true
