esphome:
  name: esphome-picow
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: True

rp2040:
  board: rpipicow

api:
  encryption:
    key: !secret picow_api_encryption_key

ota:
  - platform: esphome
    password: !secret picow_ota_password

logger:

packages:
  diagnostics: !include ../device_config/diagnostics.yaml
  status_led: !include
    file: ../../modules/status_led/status_led.yaml
    vars:
      pin_number: 32