<<: !include ./picow.yaml

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret backup_wifi_ssid
      password: !secret backup_wifi_password
  power_save_mode: none
  fast_connect: false
  manual_ip:
    static_ip: 192.168.1.88
    gateway: 192.168.1.1
    subnet: 255.255.255.0
